module.exports = {
  extends: ["@commitlint/config-conventional"],
  ignores: [
    (message) => message.includes("WIP"),
    (message) => message.includes("[skip ci]"),
    (message) => message.includes("[ci skip]"),
    (message) => message.startsWith("Merge"),
    (message) => message.includes("--wip"),
    (message) => message.includes("fixup!"),
    (message) => message.includes("squash!"),
    (message) => /^Revert/.test(message),
    (message) => /^chore\(release\):/.test(message)
  ],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore",
        "revert",
        "update",
        "add",
        "remove",
        "enhance",
        "implement",
        "optimize",
        "upgrade",
        "migrate",
        "sync",
        "bump",
        "disable",
        "enable",
        "consolidate",
        "cleanup",
        "improvement",
        "security",
        "deps",
        "config",
        "release",
        "hotfix",
        "wip",
        "merge",
        "codegen"
      ]
    ],
    "subject-case": [2, "never", ["start-case", "pascal-case", "upper-case"]],
    "subject-max-length": [2, "always", 100],
    "body-max-line-length": [2, "always", 100],
    "header-max-length": [2, "always", 100],
    "body-empty": [1, "never"],
    "footer-max-line-length": [2, "always", 100],
    "body-leading-blank": [2, "always"],
    "footer-leading-blank": [2, "always"]
  }
};
